### ISSUE TITLE
ERROR XSLTProcessor: Problems creating an XSLTProcessor.  org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 39; Premature end of file

### ISSUE THREAD

**Issue by Deepak-nebhwani** [elsevierlabs-os/spark-xml-utils#1]
I am facing issue while running basic example for xslt transformation
Stack Trace: 
Error on line 1 column 39 
  SXXP0003: Error reported by XML parser: Premature end of file.
20/05/27 19:55:12 ERROR XSLTProcessor: Problems creating an XSLTProcessor.  org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 39; Premature end of file.
net.sf.saxon.s9api.SaxonApiException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 39; Premature end of file.
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:742)
	at com.elsevier.spark_xml_utils.xslt.XSLTProcessor.init(XSLTProcessor.java:167)
	at com.elsevier.spark_xml_utils.xslt.XSLTProcessor.getInstance(XSLTProcessor.java:114)
	at xsltPoc.XsltPoc$.delayedEndpoint$xsltPoc$XsltPoc$1(XsltPoc.scala:12)
	at xsltPoc.XsltPoc$delayedInit$body.apply(XsltPoc.scala:6)
	at scala.Function0$class.apply$mcV$sp(Function0.scala:34)
	at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.App$$anonfun$main$1.apply(App.scala:76)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
	at scala.App$class.main(App.scala:76)
	at xsltPoc.XsltPoc$.main(XsltPoc.scala:6)
	at xsltPoc.XsltPoc.main(XsltPoc.scala)
Caused by: net.sf.saxon.trans.XPathException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 39; Premature end of file.
	at net.sf.saxon.event.Sender.sendSAXSource(Sender.java:447)
	at net.sf.saxon.event.Sender.send(Sender.java:164)
	at net.sf.saxon.style.StylesheetModule.loadStylesheet(StylesheetModule.java:231)
	at net.sf.saxon.style.Compilation.compileSingletonPackage(Compilation.java:106)
	at net.sf.saxon.s9api.XsltCompiler.compile(XsltCompiler.java:739)
	... 13 more
Caused by: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 39; Premature end of file.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(Unknown Source)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(Unknown Source)

Code:

import org.apache.spark.sql.SparkSession
import com.elsevier.spark_xml_utils.xslt.XSLTProcessor

object XsltPoc extends App {

   val spark = SparkSession.builder().appName("xslt-transform").config("spark.master","local").getOrCreate()
  val stylesheet = spark.sparkContext.textFile("example.xslt").collect.head
	val proc = XSLTProcessor.getInstance(stylesheet)
	//val localSrctitles = xmlfile.map(rec => proc.transform(rec._2))
	
   //localSrctitles.foreach { println }
}

Xml and XSLT files are attached in text format

[examplexml.txt](https://github.com/elsevierlabs-os/spark-xml-utils/files/4689397/examplexml.txt)
[examplexslt.txt](https://github.com/elsevierlabs-os/spark-xml-utils/files/4689404/examplexslt.txt)

**Comment by antonyscerri** [comment]
Hi

I believe your problem is reading in your XSLT file. It's reading it in as a set of lines, and you are just picking the first line with collect.head. You should switch to an alternative suitable for your environment to load the whole file into a single string. Hope that helps.

Tony

**Comment by Deepak-nebhwani** [comment]
Thanks for very quick response Tony.

Yes you are right, 

issue is with reading only first line instead of complete XSLT. however i was able to identify issue, but could not reply as quick as you respond. 
Thanks :)
